name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" #  12 hour cd :D
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: xnoctra
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
            dist/ocean.gif

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Generate Snake Animation'
          add: "dist"
